[package]
name = "tofino"
version = "0.1.0"
edition = "2021"

[features]
regmap = []

[lib]
name = "tofino"
path = "src/lib/lib.rs"

[[bin]]
name = "tftool"
path = "src/tftool/main.rs"

[dependencies]
anyhow = "1.0.52"
structopt = { version = "0.3" }
chrono = "0.4"
[target.'cfg(target_os = "illumos")'.dependencies]
illumos-devinfo = { git = "https://github.com/oxidecomputer/illumos-devinfo", branch = "main" }

[build-dependencies]
cc = "1.0"
