[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.dependencies]
anyhow = "1.0.52"
cc = "1.0"
chrono = "0.4"
illumos-devinfo = { git = "https://github.com/oxidecomputer/illumos-devinfo", branch = "main" }
structopt = "0.3.24"
tofino = { path = "crates/tofino" }
